[package]
name = "runtime"
version = "1.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
testing-utils = [
    # "substrate-subxt/client",
    # "substrate-subxt-client",
    "tempdir",
    "interbtc",
    "rand",
]
standalone-metadata = []
parachain-metadata-kintsugi = []
parachain-metadata-testnet = []

[dependencies]
tracing = { version = "0.1", features = ["log"] }

serde = { version = "1.0.130", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"] }
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.71"
tokio = { version = "1.0", features = ["full"] }
backoff = { version = "0.3.0", features = ["tokio"] }
futures = "0.3.5"
clap = "3.0.0-beta.2"
log = "0.4.0"
url = "2"
cfg-if = "1.0"

# Substrate dependencies
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

# Subxt dependencies
# https://github.com/interlay/subxt/tree/polkadot-v0.9.16
subxt = { package = "subxt", git = "https://github.com/interlay/subxt", rev = "38258d5177319c97789dc18fbcca6f99bf36af65" }
subxt-client = { package = "subxt-client", git = "https://github.com/interlay/subxt", rev = "38258d5177319c97789dc18fbcca6f99bf36af65" }

jsonrpsee = { version = "0.8.0", features = ["macros", "jsonrpsee-types", "client", "jsonrpsee-ws-client", "jsonrpsee-client-transport"] }

# Polkadot dependencies
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.16" }

bitcoin = { path = "../bitcoin"}

# Dependencies for the testing utils for integration tests
tempdir = { version = "0.3.7", optional = true }
interbtc = { package = "interbtc-standalone", git = "https://github.com/interlay/interbtc", rev = "9fed496a74c9b2b8bc0a3ed15e35804f79c79728", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.primitives]
git = "https://github.com/interlay/interbtc"
rev = "9fed496a74c9b2b8bc0a3ed15e35804f79c79728"
package = "interbtc-primitives"

[dependencies.module-bitcoin]
git = "https://github.com/interlay/interbtc"
rev = "9fed496a74c9b2b8bc0a3ed15e35804f79c79728"
package = "bitcoin"

[dependencies.module-btc-relay]
git = "https://github.com/interlay/interbtc"
rev = "9fed496a74c9b2b8bc0a3ed15e35804f79c79728"
package = "btc-relay"

[dependencies.module-oracle-rpc-runtime-api]
git = "https://github.com/interlay/interbtc"
rev = "9fed496a74c9b2b8bc0a3ed15e35804f79c79728"
package = "module-oracle-rpc-runtime-api"

[dev-dependencies]
runtime = { path = ".", features = ["testing-utils"] }
tempdir = "0.3.7"
env_logger = "0.8.3"